###
GET http://localhost:9090 HTTP/1.1
content-type: application/json

###
GET http://localhost:9090/sciences-member
content-type: application/json

###
GET http://localhost:9090/engineer-member
content-type: application/json
